#!/bin/bash
# Using wpctl for PipeWire
volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')
muted=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -o "MUTED")

if [ "$muted" = "MUTED" ]; then
    echo "Muted"
else
    echo "${volume}"
fi
